language: rust
env:
  global:
  - PROJECT_NAME=json_typegen

matrix:
  include:
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
    before_script: rustup target add $TARGET
    addons:
      apt:
        packages:
        - musl-tools
        - libssl-dev
  - os: osx
    rust: stable
    env: TARGET=x86_64-apple-darwin

script: ci/script.sh
before_deploy: ci/before_deploy.sh

deploy:
  provider: releases
  file: deployment/${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    branch: master
    tags: true
  api_key:
    secure: Bba71IsX6ZOeJQrASr/aluOSEXPdhTJNSQ+8kG1STCjx4eiiMX96YrhIFwdUb5e7rRmKG+xmKXE48DzOF0QhrY1n7AAl6rWgCIjgcRupTknrdG7S/EFzJrJnArfj2zPbH7v9+kHBG7DGyAe9bFL3EAkeT/6I11ZUf21QuSx2wslWpuGJDC/yld0Fhq3cF0sKWNhntDkHrjImg6loF6XWkTV/rDGL4I5xkz1J7aK5s99w/dmcltWSPLs1Isu10UNb34+mDkk3OMKhO/u+arGkWY1NjfG9UahHEvyr9HMZlHsd3YH3uTixUe6ymMIHqcfU8MKMTnlrH6ItuX1kwnTbB8gkqQprE+gacKbqn+MxA4m5G880CpKkfh1r4E4uLuKSM8w4DGXrRfEPzqBy8He7H46M0mg8u2nRgyOkr0lf/4TTF2bXHpHmOwy02wZA9axWZFbi2GFRKuOjkUEbDku2ww5Z6uMOpSAorFs/z+AWrn9q7SxbYUGjMB72ycqPOenkjU5fP9i0UYLMHL0z0S/610/lEBGEbFv22HB+mASx1NICHVLgHlQ9liU24ENLFA8qfzTpaVyKT6l0FS+8GuKo6p/6PkURxxu3LnIiFyNYC6Wg0XYu14PgJG8yx4I32nbJgkkF/thJKFLWwqr9s7NITwOhjldfF3g1zTe6V/8W4C8=

cache:
  directories:
  - /home/travis/.cargo

notifications:
  email:
    on_success: never
