export const WorkerMessage = {
  WASM_READY: 'WASM_READY',
  CODEGEN: 'CODEGEN',
  CODEGEN_COMPLETE: 'CODEGEN_COMPLETE',
  LOAD_FILE: 'LOAD_FILE',
  LOAD_FILE_COMPLETE: 'LOAD_FILE_COMPLETE',
  CLEAR_FILE: 'CLEAR_FILE',
}
